### ISSUE TITLE
TOKENOMICS -- TOKEN ECONOMICS 

### ISSUE THREAD

**Issue by destinyae** [availproject/docs#236]
https://twitter.com/AvailProject/status/1713960787083952466?t=F90CDrnqYqDIrpRYw5f0Xw&s=19

This is a post made by the official Avail twitter, posted on the 16th of October, 2023. 

You said you will share more including Incentivisation models, tokenomics and key details.

Not gonna lie, I have been searching for the Avail tokenomics for a long while now, haven't seen any.

I have checked the website and the docs, still none.
Or is there a tokenomics written somewhere that I don't know of? Please I'd love to know and see.

Are you still working on it or something?

I don't know if it has been drafted out already but it will be good if it's in the docs or on the Avail website for easy access.

And if it's out already, it should be visible please and open to everyone.

Thank you.

**Comment by destinyae** [comment]
Tried creating a pull request for the Avail Tokenomics to be added to the docs, and it says i must be a contributor.

**Comment by malutki880** [comment]
up
