### ISSUE TITLE
Most of the documentation are missing 

### ISSUE THREAD

**Issue by Speedevs** [availproject/docs#240]
Hey I came to report most of the documentation are missing and already SEO

https://docs.availproject.org/clash-of-nodes/madara-karnot
(Cannot be found)

https://docs.availproject.org/category/become-a-validator

(Cannot be found)

https://docs.availproject.org/about/nomination-pools

(Cannot be found)

Mostly links here

https://docs.availproject.org/docs/clash-of-nodes/challenges

Hope the team fixes this
![Screenshot_20240220_171632_Chrome](https://github.com/availproject/docs/assets/45816964/73ec7780-adae-4344-b3bd-fc212b754a1f)

**Comment by prabal-banerjee** [comment]
Works as intended
